### PR TITLE
Add check and fix for longer reports.

### PR DESCRIPTION
**Pull request by agittins**
At least some versions of iOS 17.5.1 send reports of 89 bytes instead of 88. This patch discards the new 6th byte so that decoding the payload completes successfully.

This change comes from @humpataa's comment on #52, and should fix Issues #52, #58, #57

### CODE REVIEW

**Comment by biemster** [comment]
Thank you for this PR! the issue definitely needs fixing, but since I want this script to be under 100 lines I can't accept adding 6 for this

**Comment by biemster** [comment]
pressed the wrong button, but this can for sure be done in one line, and bonus points if you can do it in zero!

**Comment by Teeed** [comment]
This works and fixes this bug, confirmed

**Comment by biemster** [comment]
Yes it does and I'll merge this in if @agittins reduces the number of lines added, otherwise I will make a new commit coming week (I've started working a bit on FindMy again)

**Comment by biemster** [comment]
Fixed in 389f301

**Pull request closed without merging**
