### PR TITLE
Requests JSON

### LINKED ISSUE #20: 400 Bad Request
```
400 Bad Request
Traceback (most recent call last):
  File "request_reports.py", line 189, in <module>
    res = json.loads(response.read())['results']
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

Have you encountered this before? I have automated the polling of this script, and had it running for a few days. It abruptly stopped and generated this error. Restarting the script made no change. If i go back to vanilla OHS and use the GUI, it updates fine.

Thanks!

Additional Info drawn from response headers.
```
[('content-length', '0'), ('via', 'xrail:st53p00ic-qujn14040502.me.com:8301:22R920:grp60,631194250daa17e24277dea86cf30319:0299c4cf8819616e8ba5700c89695c8d:jptyo12'), ('access-control-expose-headers', 'X-Apple-Request-UUID,Via'), ('strict-transport-security', 'max-age=31536000; includeSubDomains;'), ('x-responding-instance', 'acsnservice:2:prod-p00-acsnservice--partial-5b7df67f59-sx8n8:80:2388B9802:6a2bc5323182'), ('server', 'AppleHttpServer/3faf4ee9434b'), ('x-apple-jingle-correlation-key', '<removed>'), ('connection', 'keep-alive'), ('apple-seq', '0'), ('x-apple-user-partition', '0'), ('date', 'Thu, 30 Mar 2023 01:23:32 GMT'), ('x-apple-request-uuid', '<removed>'), ('apple-tk', 'false'), ('apple-originating-system', 'UnknownOriginatingSystem'), ('x-apple-edge-response-time', '168')]
```

### PR DESCRIPTION
**Pull request by webjay**
- sends data as JSON. (https://requests.readthedocs.io/en/latest/_modules/requests/api/#post)
- added `.gitignore` to ignore key files.
- added `requirements.txt` for `pip install --requirement`

Closes #20

### CODE REVIEW

**Comment by biemster** [comment]
That's a really elegant fix, thanks! I will merge this when I have a fix for the main branch as well, otherwise they might stay out of sync for quite a while (although I'm also not sure that having both branches broken is better than only one, but that's how my personal time management works nowadays :( )

**Comment by webjay** [comment]
An idea is to rename main to python2 and let monterey become main.

**Comment by biemster** [comment]
yeah that's definitely an idea. The initial plan was to make a minimal Catalina disk based on the BaseSystem.dmg, but it's not very likely anymore that that is ever going to happen. Still, Docker-OSX recommends Catalina (last time I checked), so I might adhere to that for a while more.

**Comment by biemster** [comment]
It's still on my list! You can reopen this if you want the credit, otherwise I'll copy the change in myself at some point.

**Comment by webjay** [comment]
oh sorry, I moved the repo to a client and added a license, which I hope you are cool with.
I have made lots of changes since, so feel free to copy:
https://github.com/SpaceInvaderTech/AppleCollector

**Comment by biemster** [comment]
Cool! that is exactly the type of project I hoped would come out of this repo. Nice work!

**Pull request closed without merging**
